// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed font/Hack-Bold.ttf
var resourceHackBoldTtfData []byte
var resourceHackBoldTtf = &fyne.StaticResource{
	StaticName:    "font/Hack-Bold.ttf",
	StaticContent: resourceHackBoldTtfData,
}

//go:embed font/Hack-BoldItalic.ttf
var resourceHackBoldItalicTtfData []byte
var resourceHackBoldItalicTtf = &fyne.StaticResource{
	StaticName:    "font/Hack-BoldItalic.ttf",
	StaticContent: resourceHackBoldItalicTtfData,
}

//go:embed font/Hack-Italic.ttf
var resourceHackItalicTtfData []byte
var resourceHackItalicTtf = &fyne.StaticResource{
	StaticName:    "font/Hack-Italic.ttf",
	StaticContent: resourceHackItalicTtfData,
}

//go:embed font/Hack-Regular.ttf
var resourceHackRegularTtfData []byte
var resourceHackRegularTtf = &fyne.StaticResource{
	StaticName:    "font/Hack-Regular.ttf",
	StaticContent: resourceHackRegularTtfData,
}
