// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceActiveEnJson = &fyne.StaticResource{
	StaticName: "active.en.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Terminal\"\n}\n"),
}
var resourceActiveFrJson = &fyne.StaticResource{
	StaticName: "active.fr.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Terminale\"\n}\n"),
}
var resourceActivePtBRJson = &fyne.StaticResource{
	StaticName: "active.pt_BR.json",
	StaticContent: []byte(
		"{\n    \"Title\": \"Fyne Terminal\"\n}\n"),
}
var resourceActiveRuJson = &fyne.StaticResource{
	StaticName: "active.ru.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Терминал\"\n}\n"),
}
var resourceActiveSkJson = &fyne.StaticResource{
	StaticName: "active.sk.json",
	StaticContent: []byte(
		"{\n    \"Title\": \"Fyne Terminál\"\n}\n"),
}
var resourceActiveUkJson = &fyne.StaticResource{
	StaticName: "active.uk.json",
	StaticContent: []byte(
		"{\n    \"Title\": \"Термінал Fyne\"\n}\n"),
}
