// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed fyne_logo.png
var fynelogoData []byte
var fynelogo = &fyne.StaticResource{
	StaticName:    "fyne_logo.png",
	StaticContent: fynelogoData,
}

//go:embed Icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "Icon.png",
	StaticContent: resourceIconPngData,
}
